title: Neverland
desc: Random thoughts from chaos
permalink: /:year/:month/:day/:title 
pygments: true
markdown: rdiscount

rdiscount:
  extensions: [strict]
production_url : http://blog.chengyichao.info
